### PR TITLE
fix(types): set compatibility with puppeteer v10

### LINKED ISSUE #33: Compatibility with puppeteer v10
Hi,

Puppeteer 10 turns out to be incompatible with types defined in Mockiavelli ([PuppeteerController.ts file](https://github.com/HLTech/mockiavelli/blob/master/src/controllers/PuppeteerController.ts#L70)). When both are used in project, following TypeScript error is shown:
```
TS2345: Argument of type 'Page' is not assignable to parameter of type 'BrowserPage'. 
Type 'Page' is not assignable to type 'PuppeteerPage'. 
Types of property 'on' are incompatible. 
Type '<K extends keyof PageEventObject>(eventName: K, handler: (event: PageEventObject[K]) => void) => EventEmitter' is not assignable to type '(eventName: "request", handler: (e: PuppeteerRequest) => void) => any'. 
Types of parameters 'handler' and 'handler' are incompatible. 
Types of parameters 'e' and 'event' are incompatible. 
Type 'HTTPRequest' is not assignable to type 'PuppeteerRequest'. 
The types returned by 'method()' are incompatible between these types. 
Type 'string' is not assignable to type '"GET" | "POST" | "PATCH" | "PUT" | "DELETE" | "OPTIONS"'.
```

Probably `method()` function return type should be widened to string to match [type defs in Puppeteer](https://github.com/puppeteer/puppeteer/blob/main/src/common/HTTPRequest.ts#L174)

### PR DESCRIPTION
**Pull request by Fiszcz**
resolve #33

### CODE REVIEW

**Review by crpc — APPROVED** [review]

**Comment by pawfa** [comment]
Last change regarding class method which returns REST method was made 14 months ago, and it was only about extracting whole class to separate module: https://github.com/puppeteer/puppeteer/blame/7e74a9d6065bef5deb1e13e9c3f77620ffab80ad/src/common/HTTPRequest.ts#L174

My question is why it failed now?

**Comment by crpc** [comment]
> Last change regarding class method which returns REST method was made 14 months ago, and it was only about extracting whole class to separate module: https://github.com/puppeteer/puppeteer/blame/7e74a9d6065bef5deb1e13e9c3f77620ffab80ad/src/common/HTTPRequest.ts#L174
> 
> My question is why it failed now?

A change you're looking for is in this commit (released in v9.0.0)
https://github.com/puppeteer/puppeteer/commit/866d34ee1122e89eab00743246676845bb065968

`page.on('request', ...)` has had its types fixed there

**Review by pawfa — APPROVED** [review]

**Comment by mex511511mno** [comment]
> > Last change regarding class method which returns REST method was made 14 months ago, and it was only about extracting whole class to separate module: https://github.com/puppeteer/puppeteer/blame/7e74a9d6065bef5deb1e13e9c3f77620ffab80ad/src/common/HTTPRequest.ts#L174
> 
> > 
> 
> > My question is why it failed now?
> 
> 
> 
> A change you're looking for is in this commit (released in v9.0.0)
> 
> https://github.com/puppeteer/puppeteer/commit/866d34ee1122e89eab00743246676845bb065968
> 
> 
> 
> `page.on('request', ...)` has had its types fixed there and since then requires HTTPRequest class object

**Comment by mex511511mno** [comment]
[s]()

**Pull request merged**
